FROM ubuntu:jammy
CMD ["apt", "update"]
CMD ["apt", "install", "php-cgi"]
CMD ["apt", "install", "python3"]
CMD ["apt", "install", "python3-pip"]
CMD ["pip", "install", "pytz"]
CMD ["pip", "install", "typer[all]"]
